[profile.default]
slow-timeout = "60s"

[[profile.default.overrides]]
filter = 'package(concord_macros) and binary(trybuild_current)'
slow-timeout = { period = "240s", terminate-after = 2 }
priority = -100
test-group = 'trybuild'

[test-groups.trybuild]
max-threads = 3
